name: Deploy Website to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run local deployment script
        run: |
          /home/ubuntu/deploy.sh website